TXT_OPERATION = "\n| Digite a operação: "
TXT_VALUE1 = "\nDigite o valor 1: "
TXT_VALUE2 = "\nDigite o valor 2: \n"
[SOMAR, MULTIPLICAR, SUBTRAIR, DIVIDIR, SAIR] = ["+", "*", "-", "/", "sair"]
TXT_INVALID_OPERATION = "\n-------------Operação Inválida-------------"
TXT_ZERO_DIVISION = "\n-------------Não é possível dividir valor por zero-------------"
TXT_OPTION_KEEP = "\nDeseja fazer outra operação? (S/N): "
TXT_NUMERIC_VAL = "Digite um valor numérico!"
TXT_NO_NEGATIVES = "Não é permitido realizar contas com resultado negativo."
